name: GitHub Actions Demo
run-name: ${{ github.actor }} build and deploy pipeline

#Triger the build pipeline when there is a merge or a push in main branch
on:
  push:
    branches:
      - main
      - "releases/**"

env:
  RESOURCE-GROUP: agri-swap
  LOCATION: southeastasia
  TEMPLATE-FILE: infrastructure/appService.bicep
  SUBSCRIPTION-ID: 59c9e792-d77c-466c-a367-de2fe70ec751
  WEBAPP-NAME: agriswap-southeastasia-819225107

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install Dependencies
        run: |
          cd my-app 
          npm install

      - name: Build application
        run: |
          cd my-app 
          npm run build
          echo "Current directory: ${pwd}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: agri-swap-front-end-artifact
          path: my-app/build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

      - name: Creating artifact zip file
        run: |
          cd my-app/build
          zip -r ../build.zip .
        working-directory: ${{ github.workspace }}/my-app/build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: "Development"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: agri-swap-front-end-artifact
          path: build

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/appService.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr:

      - name: Publish Website to Web App
        uses: Azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deployment source config-zip \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --name ${{ env.WEBAPP-NAME }} \
            --src build.zip \
            --output json
