name: GitHub Actions Demo
run-name: ${{ github.actor }} build and deploy pipeline

# Trigger the build pipeline when there is a merge or a push in main branch
on:
  push:
    branches:
      - main
      - "releases/**"

env:
  RESOURCE-GROUP: agriswap-group
  LOCATION: eastasia
  TEMPLATE-FILE: infrastructure/appService.bicep
  SUBSCRIPTION-ID: 59c9e792-d77c-466c-a367-de2fe70ec751
  STATIC-WEB-APP-NAME: agriswap-eastasia-3184826203

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install Dependencies
        run: |
          cd agrswapapp
          npm install

      - name: Build application
        run: |
          cd agrswapapp
          npm run build
          echo "Current directory: ${pwd}"

      - name: Creating artifact zip file
        run: |
          cd agrswapapp
          zip -r ../build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: agri-swap-front-end-artifact
          path: build.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: "Development"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: agri-swap-front-end-artifact
          path: agri-swap-front-end-artifact

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Use the secret containing Service Principal credentials

      - name: Deploy static web app
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # Use the secret containing GitHub PAT
        run: |
          az staticwebapp create --name ${{ env.STATIC-WEB-APP-NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --source https://github.com/EternalRex/agr-swap.git --branch main --location ${{ env.LOCATION }}
