name: GitHub Actions Demo
run-name: ${{ github.actor }} build and deploy pipeline

#Triger the build pipeline when there is a merge or a push in main branch
on:
  push:
    branches:
      - main
      - "releases/**"

env:
  RESOURCE-GROUP: agriswap-group
  LOCATION: eastasia
  TEMPLATE-FILE: infrastructure/appService.bicep
  SUBSCRIPTION-ID: 59c9e792-d77c-466c-a367-de2fe70ec751
  STATIC-WEB-APP-NAME: agriswap-eastasia-3184826203

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install Dependencies
        run: |
          cd agrswapapp
          npm install

      - name: Build application
        run: |
          cd agrswapapp
          npm run build
          echo "Current directory: ${pwd}"

      - name: Creating artifact zip file
        run: |
          cd agrswapapp
          zip -r ../build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: agri-swap-front-end-artifact
          path: build.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: "Development"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: agri-swap-front-end-artifact
          path: agri-swap-front-end-artifact

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/appService.bicep
          parameters: |
            "staticWebAppName=${{ env.STATIC-WEB-APP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr:

      - name: Deploy static web app
        run: |
          az staticwebapp create --name ${{ env.STATIC-WEB-APP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --source . --location ${{ env.LOCATION }} --app-agri-swap-front-end-artifact .
